server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: qxx
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual # 选择手动ack